'use strict'

module.exports = {
  env: {
    node: true
  },

  plugins: [
    'import-alias',
    'simple-import-sort',
  ],

  rules: {
    'no-console': [process.env.NODE_ENV === 'development' ? 'off' : 'error', { allow: ['warn', 'error'] }],
    'no-debugger': process.env.NODE_ENV === 'development' ? 'off' : 'error',
    camelcase: 'off',
    'arrow-parens': ['error', 'as-needed'],
    'import-alias/import-alias': ['error', { relativeDepth: 0, aliases: [{ alias: '@', matcher: '^src' }] }],
    'import/extensions': ['error', 'always', { js: 'never', ts: 'never', cjs: 'never', cts: 'never', mjs: 'never', mts: 'never', jsx: 'never', tsx: 'never' }],
    'simple-import-sort/imports': ['error',
      {
        groups: [
          ['^vue', '^@?\\w'],
          ['^@/(?!pages|components|assets)\\w+'],
          ['^@/pages/'],
          ['^@/components/'],
          ['^@/assets/'],
          ['^\\u0000'],
          ['^\\.\\.(?!/?$)', '^\\.\\./?$'],
          ['^\\./(?=.*/)(?!/?$)', '^\\.(?!/?$)', '^\\./?$'],
          ['^.+\\.?(css|styl|sass)$']
        ]
      }
    ],
    'simple-import-sort/exports': 'error',
    'prefer-template': 'error',
    'vue/array-bracket-spacing': ['error', 'never'],
    'vue/arrow-spacing': ['error'],
    'vue/block-spacing': ['error'],
    'vue/brace-style': ['error', '1tbs', { allowSingleLine: true }],
    'vue/comma-dangle': ['error'],
    'vue/comma-spacing': ['error'],
    'vue/comma-style': ['error'],
    'vue/component-tags-order': ['error', { order: ['template', 'script', 'style'] }],
    'vue/custom-event-name-casing': ['error', 'kebab-case'],
    'vue/dot-location': ['error', 'property'],
    'vue/dot-notation': ['error'],
    'vue/eqeqeq': ['error', 'always', { null: 'ignore' }],
    'vue/first-attribute-linebreak': ['error', { singleline: 'beside', multiline: 'beside' }],
    'vue/func-call-spacing': ['error'],
    'vue/html-closing-bracket-newline': ['error', { singleline: 'never', multiline: 'never' }],
    'vue/key-spacing': ['error'],
    'vue/keyword-spacing': ['error'],
    'vue/multiline-html-element-content-newline': 'error',
    'vue/multiline-ternary': ['error', 'always-multiline'],
    'vue/new-line-between-multi-line-property': 'error',
    'vue/no-constant-condition': ['error', { checkLoops: false }],
    'vue/no-deprecated-filter': 'error',
    'vue/no-deprecated-slot-scope-attribute': 'error',
    'vue/no-empty-component-block': 'error',
    'vue/no-empty-pattern': ['error'],
    'vue/no-extra-parens': ['error', 'functions'],
    'vue/no-irregular-whitespace': ['error'],
    'vue/no-loss-of-precision': ['error'],
    'vue/no-required-prop-with-default': 'error',
    'vue/no-sparse-arrays': ['error'],
    'vue/no-static-inline-styles': 'error',
    'vue/no-this-in-before-route-enter': 'error',
    'vue/no-undef-components': ['error', { ignorePatterns: ['router(\\-\\w+)+', 'VTooltip', 'i18n'] }],
    'vue/no-useless-mustaches': 'error',
    'vue/object-curly-newline': ['error', { multiline: true, consistent: true }],
    'vue/object-curly-spacing': ['error', 'always'],
    'vue/object-property-newline': ['error', { allowMultiplePropertiesPerLine: true, allowAllPropertiesOnSameLine: false }],
    'vue/object-shorthand': ['warn', 'properties'],
    'vue/operator-linebreak': ['error', 'after', { overrides: { '?': 'before', ':': 'before', '|>': 'before' } }],
    'vue/padding-line-between-blocks': 'error',
    'vue/prefer-separate-static-class': 'error',
    'vue/prefer-template': 'error',
    'vue/quote-props': ['error', 'as-needed'],
    'vue/require-default-prop': 'error',
    'vue/require-direct-export': 'error',
    'vue/require-explicit-emits': 'error',
    'vue/singleline-html-element-content-newline': 'error',
    'vue/space-in-parens': ['error', 'never'],
    'vue/space-infix-ops': ['error'],
    'vue/space-unary-ops': ['error', { words: true, nonwords: false }],
    'vue/template-curly-spacing': 'error',
    'vue/v-for-delimiter-style': 'error',
  },

  ignorePatterns: [
    'dist/',
  ],
}
